version: '2'
services:
  nginx:
    tty: true
    stdin_open: true
    image: nginx
    volumes:
      - ./files/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "443:443"
    links:
      - suchwowapp

  suchwowapp:
    tty: true
    stdin_open: true
    image: m1dn/suchwowapp:master
    ports:
      - "8080:8080"
    environment:
      - RAILS5APP_DATABASE_HOST='pg'
      - RAILS5APP_DATABASE_PASSWORD='thisisnotthebestpasswordintheworldthisisjustatribute'
      - DISABLE_DATABASE_ENVIRONMENT_CHECK=1
    command:
      - bundle exec rake db:schema:load && bundle exec rake db:migrate && bundle exec unicorn -p 8080
    links:
      - pg

  pg:
    tty: true
    stdin_open: true
    image: postgres:9.5
    environment:
      - POSTGRES_USER=rails5app
      - POSTGRES_DB=rails5app_production
      - POSTGRES_PASSWORD=thisisnotthebestpasswordintheworldthisisjustatribute
